; Este arquivo serve para listar os mapas quando utilizamos o comando "amxmodmenu" no console para admistrar o servidor
; Caso adicione mais algum mapa na pasta do cs, você deve colocar o nome do mapa aqui para ele ser listado

; Maps configuration file
; File location: $moddir/addons/amxmodx/configs/maps.ini
; To use with Maps Menu plugin

; Add in your mod's maps here
; Delete this file to use mapcycle.txt

35hp
aim_ak-colt
aim_ak_vs_m4a1
aim_headshot
aim_map
as_oilrig
awp_africa
awp_athon2k
awp_aztec
awp_city
awp_city2
awp_digital
awp_false
awp_india
awp_italy
awp_japan
awp_map
awp_map2
awp_map2b
awp_map3
awp_map5
awp_map_alk
awp_map_fair
awp_map_millenium
awp_map_mind
awp_mario
awp_militia
awp_minimilitia
awp_monopoly
awp_monopoly_v2
awp_snowcliffs
awp_snowfun
awp_spike
awp_warzone
cs_747
cs_assault
cs_backalley
cs_bank
cs_rio
cs_estate
cs_havana
cs_italy
cs_chaves
cs_militia
cs_office
cs_siege
cs_mansion_novi
css_dust2sky_go
de_airstrip
de_aztec
de_cbble
de_chateau
de_chaves
de_dust
de_dust2
de_dust2_so_fundo
de_dust2_2x2
de_dust2_fundo
de_inferno
de_nuke
de_piranesi
de_prodigy
de_rats
de_rats3
de_storm
de_survivor
de_torn
de_train
de_vertigo
fy_baga_4p_xmas
fy_arena_ak47
fy_iceworld
fy_iceworld2k
fy_iceworld3
fy_pool2k
fy_pool_day
fy_pool_day2
fy_snow
he_dodgeball2
he_tennis
ka_construct
ka_dust
knife_zone
surf_ski
surf_ski_2
Tr_Colt