; NÃO ESQUEÇA DE TIRAR O ";" (ponto e virgula) da frente para que os models se apliquem
; Siga os exemplo abaixo:

; Exemplo1: "models/v_awp.mdl" "models/SuaPasta/v_awp.mdl" // Subistitue para todos no server.


; O Mesmo pode ser feito com sons, Siga um Exemplo:
; "sound/weapons/sound.wav" "sound/weapons/newsound.wav" "CT"

; Você Pode Modificar os Models Abaixo Com Diretorio das Armas que você quer Desativar
; "models/v_glock18.mdl"  = é o nome da pasta que esta a skin e o nome da skin original do jogo
; "models/newSkins_Deivid/glock18/v_glock18.mdl  =  "admodels" é o nome da pasta original do jogo, "newSkins_Deivid" o nome da sua pasta
; que vc criou dentro de "admodel" e "glock18" é o nome da pasta que esta sua skin, por fim "v_glock18.mdl" é o nome da skin


; Nota: dentro da pasta de skin vc vai econtra v_nomeSkin.mdl, w_nomeSkin.mdl  e p_nomeSkin.mdl.
; Cada arquivo desse representa a posição da arma, por exemplo: 

; v_nomeSkin.mdl = o braço segurando a arma
; w_nomeSkin.mdl = é quando a arma está jogada no chão
; p_nomeSkin.mdl = é quando a arma esta apontada pra vc, qnd esta de frente para o oponente.

; PORÉM COLOCAR TODAS AS MODELS VAI DEIXAR SEU SERVER LENTO PARA FAZER DOWNLOAD NO MAQUINA DOS AMIGOS 

; ATENÇÃO O NÍVEL MÁXIMO DE PASTA PARA CHEGAR ATÉ O ARQUIVO ".mdl" É 3 (contando com a Models)
; CASO VC COLOQUE MAIS DE 3 NÍVEIS A KINS NÃO VAI FUNCIONAR 

; EXEMPLO ERRADO!

;"models/v_glock18.mdl" "models/newSkins_Deivid/pistola/glock18/v_glock18.mdl"
;"models/w_glock18.mdl" "models/newSkins_Deivid/pistola/glock18/w_glock18.mdl"

;Perceba que no exemplo a cima tive que percorrer 4 níveis de pasta: models, newSkins_Deivid, pistola e glock18 até chegar no arquivo ".mdl"
;Isso da bug e não acontece a troca da skin

;EXEMPLO CORRETO!

;"models/v_glock18.mdl" "models/newSkins_Deivid/glock18/v_glock18.mdl"
;"models/w_glock18.mdl" "models/newSkins_Deivid/glock18/w_glock18.mdl"


;============================== ADD SKINS NO SERVER ==========================

; Arma TR "ak47" SKIN VERMELHA
"models/p_ak47.mdl" "models/newSkins_Deivid/ak47/p_ak47.mdl"
"models/v_ak47.mdl" "models/newSkins_Deivid/ak47/v_ak47.mdl"
"models/w_ak47.mdl" "models/newSkins_Deivid/ak47/w_ak47.mdl"

; Arma CT "Coult m4a1" SKIN ROSA E ROXO (add na pasta mexendo)
"models/p_m4a1.mdl" "models/newSkins_Deivid/m4a1/p_m4a1.mdl"
"models/v_m4a1.mdl" "models/newSkins_Deivid/m4a1/v_m4a1.mdl"
"models/w_m4a1.mdl" "models/newSkins_Deivid/m4a1/w_m4a1.mdl"

; Arma CT e TR "Desert" (add na pasta mexendo, coloar os sons dela tbm)
"models/v_deagle.mdl" "models/newSkins_Deivid/desert/v_deagle.mdl" 
"models/w_deagle.mdl" "models/newSkins_Deivid/desert/w_deagle.mdl"

; Faca SKIN VERMELHA
"models/v_knife.mdl" "models/newSkins_Deivid/faca/v_knife.mdl"


; Bomba Explosão
"models/v_hegrenade.mdl" "models/newSkins_Deivid/bomba/v_hegrenade.mdl"
"models/w_hegrenade.mdl" "models/newSkins_Deivid/bomba/w_hegrenade.mdl"

; Bomba Flash Branco
"models/v_flashbang.mdl" "models/newSkins_Deivid/bomba/v_flashbang.mdl"
"models/w_flashbang.mdl" "models/newSkins_Deivid/bomba/w_flashbang.mdl"

; Bomba Fumaça
"models/v_smokegrenade.mdl" "models/newSkins_Deivid/bomba/v_smokegrenade.mdl"
"models/w_smokegrenade.mdl" "models/newSkins_Deivid/bomba/w_smokegrenade.mdl"

; Som de Armas
;"sound/weapons/somOriginal.wav" "sound/weapons/novoSom.wav"

; #######################  ATENÇÃO  #######################


; 1- Os sons das armas ou bombas geralmente são configurados para fazer a leitura na pasta "weapons"
; Porém você pode verificar qual caminho do som (caso tenha sons personalizados) decompilando o arquivo ".mdl"

; 2- Note que na troca do arquivo original pela skin nova, eu coloquei o mesmo nome do original e do novo para substituição
; Exemplo: "v_hegrenade.mdl" na pasta original continuou sendo "v_hegrenade.mdl" na pasta de novas skins.
; Caso você for trocar a skin pela segunda vez, provavelmente o servidor vai ler a skin antiga, se isso acontecer, mude o nome da sua nova skin
; por exemplo pode colocar um "_mod" no fim dela, assim :

; v_smokegrenade_mod.mdl 

; DEPOIS DE MUDAR O NOME DELA, FAÇA A ALTERAÇÃO AQUI NA LINHA DE CÓDIGO, SALVE E 

; REINICIE O SERVIDOR PARA VER SE APLICOU.  




