; AMX Mod X plugins

; ATIVAR MENU AMX NO JOGO => No Console: amxmodmenu
; Saia do Console "ESC" e o Menu estará na tela 
; Com este Menu você pode trocar mapa, Kikar Jogadores, Etc..


; Admin Base - Always one has to be activated
admin.amxx		        ; admin base (required for any admin-related)
;autolang.amxx		    ; detecta a linguagem automaticamente
;admin_sql.amxx		    ; admin base - SQL version (comment admin.amxx)

; Habilite para usar plugins de amx mod.
;amxmod_compat.amxx	    ; AMX Mod backwards compatibility layer

; Basic
admincmd.amxx		    ; basic admin console commands
;adminhelp.amxx		    ; help command for admin console commands
adminslots.amxx		    ; slot reservation
multilingual.amxx	    ; Multi-Lingual management
amx_exec.amxx		    ; executa comandos
announce_admins_entrance.amx  ; Avisa quando adm entra no server

; Menus
menufront.amxx		    ; front-end for admin menus
cmdmenu.amxx		    ; command menu (speech, settings)
plmenu.amxx		        ; players menu (kick, ban, client cmds.)
telemenu.amxx		    ; teleport menu (Fun Module required!)
mapsmenu.amxx		    ; maps menu (vote, changelevel)
pluginmenu.amxx		    ; Menus for commands/cvars organized by plugin

; Chat / Messages
adminchat.amxx		    ; console chat commands
antiflood.amxx		    ; prevent clients from chat-flooding the server
scrollmsg.amxx		    ; displays a scrolling message (habilitado no outro)
imessage.amxx		    ; displays information messages
adminvote.amxx		    ; vote commands

; Map related
nextmap.amxx		    ; displays next map in mapcycle
mapchooser.amxx		    ; allows to vote for next map
timeleft.amxx		    ; displays time left on map
night_day.amxx          ; Vote map dia e noite (inicia automaticamente em toda troca de mapa)

; Configuration
pausecfg.amxx		    ; allows to pause and unpause some plugins
statscfg.amxx		    ; allows to manage stats plugins via menu and commands

; Padrão
admin_execall.amxx	    ; Executa comandos cliente
say_amx_old.amxx	    ; Say de amxmod 2006.3

; Counter-Strike
restmenu.amxx		    ; restrict weapons menu
statsx.amxx		        ; stats on death or round end (CSX Module required!)
stats_logging.amxx	    ; weapons stats logging (CSX Module required!) (habilitado no outro)

; Plugins [Servidor]
hpk.amxx		        ; Kika jogadores com anti-ping alto
voteban.amxx		    ; faz voteban caso não haja ADMIN
connect_announce.amxx	; Anuncia a entrada de novos jogadores
deagsmapmanager.amxx	; mostra o próximo mapa na tela
;country_kicker.amxx	; kika jogadores que nao pertencem ao nosso país

; Plugins - [Estatísticas]:
aposta.amxx		        ; faça apostas
c4timer.amxx		    ; timer da C4 até explodir
plugin-shot.amxx 	    ; Mostra o dano tirado do adversário

; Plugins - [Efeitos]
skull.amxx              ; aparece uma caveira quando morre
amx_gore_ultimate.amxx	; Mais sangue! vide config em server.cfg
nadedrop.amxx		    ; dropa granada do jogador morto no chão
;paintball.amxx		    ; tiros coloridos
advanced_tracers.amxx	; mostra os rastros das balas
grenade_trail.amxx      ; trajetória das granadas
;frostnades.amxx	    ; substitua a smoke grenade por uma congelante
event_sounds.amxx       ; Som no inicio do jogo, HeadShot, Multikill, etc (para conf vide event_sounds.ini)

; Plugins - [Personalização]
backweapons.amxx	    ; arma primária nas costas
camera.amxx		        ; visualize seu personagem em 3ª pessoa (No chat: /camera)
amx_parachute.amxx	    ; pule de paraquedas no cs (segure tecla E) somente adm do server
sillyc4.amxx		    ; Plante a C4 na parede
speclist.amxx		    ; mostra seus espectadores
damage_glow.amxx	    ; mostra o dano causado em glow
unlimited_money.amxx  	; dinheiro maior que 16000
amx_plant_bonus.amxx	; plante a C4 e ganhe bonus em $
menu_armas.amxx         ; Mostra menu rapido para comprar arma e bomba (inicia automaticamente nas partidas! No Chat: /armas ou N)
admodels.amxx		    ; Adm´s podem escolher 4 skins de personagens (somente adm´s! No Chat: /admodels ou V)
skin_armas.amxx         ; Adm,s podem habilitar ou desabilitar skins de armas (vide arquivo "novas_armas.ini" No Chat: /skin)
semiclip.amxx		; Atravessar Jogadores da mesma equipe para não trombarem (os jogadores ficam transparente, "team_semiclip.cfg")


; Custom - Add 3rd party plugins here